name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux builds
          - os: ubuntu-latest
            arch: x64
            artifact_name: rime-deploy-linux-x64
            cc: gcc
          - os: ubuntu-latest
            arch: arm64
            artifact_name: rime-deploy-linux-arm64
            cc: aarch64-linux-gnu-gcc
          - os: ubuntu-latest
            arch: arm
            artifact_name: rime-deploy-linux-arm
            cc: arm-linux-gnueabihf-gcc
          
          # macOS builds
          - os: macos-latest
            arch: x64
            artifact_name: rime-deploy-macos-x64
            cc: clang
          - os: macos-latest
            arch: arm64
            artifact_name: rime-deploy-macos-arm64
            cc: clang
            
          # Windows builds
          - os: windows-latest
            arch: x64
            artifact_name: rime-deploy-windows-x64.exe
            cc: gcc
          - os: windows-latest 
            arch: arm64
            artifact_name: rime-deploy-windows-arm64.exe
            cc: gcc
          - os: windows-latest
            arch: arm
            artifact_name: rime-deploy-windows-arm.exe
            cc: gcc

    steps:
      - uses: actions/checkout@v4
      
      # 设置 QEMU
      - name: Set up QEMU
        if: matrix.arch == 'arm64' || matrix.arch == 'arm'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      
      - name: Setup Build Environment
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y build-essential
            if [ "${{ matrix.arch }}" = "arm64" ]; then
              sudo apt-get install -y gcc-aarch64-linux-gnu
            elif [ "${{ matrix.arch }}" = "arm" ]; then
              sudo apt-get install -y gcc-arm-linux-gnueabihf
            fi
          fi
      
      - name: Build
        shell: bash
        env:
          CC: ${{ matrix.cc }}
        run: |
          mkdir -p build artifacts
          
          if [ "${{ matrix.arch }}" = "arm64" ] || [ "${{ matrix.arch }}" = "arm" ]; then
            if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
              make CC=${{ matrix.cc }}
            else
              make
            fi
          else
            make
          fi
          
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp rime-deploy.exe artifacts/${{ matrix.artifact_name }}
          else
            cp rime-deploy artifacts/${{ matrix.artifact_name }}
            chmod +x artifacts/${{ matrix.artifact_name }}
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rime-deploy-${{ matrix.os }}-${{ matrix.arch }}
          path: artifacts/*
        
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
