name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          
  build-release:
    needs: release
    name: Build Release on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: rime-deploy-linux
            asset_name: rime-deploy-linux-x64
          - os: macos-latest
            artifact_name: rime-deploy-macos
            asset_name: rime-deploy-macos-x64
          - os: windows-latest 
            artifact_name: rime-deploy-windows.exe
            asset_name: rime-deploy-windows-x64.exe
            
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: |
        mkdir build && cd build
        cmake ..
        cmake --build . --config Release
        
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: build/Release/${{ matrix.artifact_name }}
