name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows builds
          - os: windows-latest
            artifact_name: rime-deploy-windows.exe
            asset_name: rime-deploy-windows-x64.exe
            
          # macOS builds  
          - os: macos-latest
            artifact_name: rime-deploy-macos
            asset_name: rime-deploy-macos-x64
            
          # Linux builds
          - os: ubuntu-latest
            artifact_name: rime-deploy-linux
            asset_name: rime-deploy-linux-x64

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Build Environment
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y build-essential
          fi
          
      - name: Build
        shell: bash
        run: |
          make
          mkdir -p artifacts
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp rime-deploy.exe artifacts/${{ matrix.artifact_name }}
          else
            cp rime-deploy artifacts/${{ matrix.artifact_name }}
            chmod +x artifacts/${{ matrix.artifact_name }}
          fi
          
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: artifacts/${{ matrix.artifact_name }}
